# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:
  en: Title
  es: Título
tagline:
  en: 'A multilingual page'
  es: 'Una página multi-idioma'
description:
  en: 'This multilingual page was made with the <a href="https://fongandrew.github.io/hydeout/" target="_blank">Hydeout</a> theme for <a href="http://jekyllrb.com" target="_blank">Jekyll</a>.'
  es: 'Esta página multi-idioma utiliza el tema <a href="https://fongandrew.github.io/hydeout/" target="_blank">Hydeout</a> para <a href="http://jekyllrb.com" target="_blank">Jekyll</a>.'
index:
  home:
    en: 'Home'
    es: 'Inicio'
  url:
    en: 
    es: 'index-es.html'
url:              https://azarrias.github.io
baseurl:          '/hydeout-multilingual'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
tags_page_url:
  en: 'tags.html'
  es: 'tags-es.html'
search_page_url:
  en: 'search.html'
  es: 'search-es.html'
feed_page_url:
  en: 'feed.xml'
  es: 'feed-es.xml'
                  
# Multilingual config
default_lang: en
languages: ["en", "es"]

author:
  name:           'Adolfo Zarrias'
  url:            https://twitter.com/adolfozt

#paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.7.0
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/azarrias/hydeout-multilingual

# For Google Analytics support, define a google_analytics 
# variable with your property ID in your config file
google_analytics: UA-90175844-2
